#!/bin/bash
if [ ! -e ~/transactionSummary/outfile ] || [ "$1" -nt ~/transactionSummary/outfile ]; then
  OUTPUT=`statement $1`
  echo "$OUTPUT" | tee ~/transactionSummary/outfile
  echo -n "Per Week: £" | tee -a ~/transactionSummary/outfile
  echo "$OUTPUT" | grep -o --regexp=-*[0-9][0-9]*.[0-9][0-9]* | paste -s -d/ |
    bc -l | grep -o --regexp=-*[0-9][0-9]*.[0-9][0-9] | head -n 1 |
    tee -a ~/transactionSummary/outfile
else
  cat ~/transactionSummary/outfile
fi
